version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      # It doesn't update the version comment for us
      - dependency-name: 'necojackarc/auto-request-review'
