name: Check C-source encoding
on: [push, pull_request]

jobs:
  check_encoding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if C-sources are US-ASCII
        run: |
          ! grep -r -n '[^	 -~]' *.[chy] include internal win32/*.[ch]
