name: Miscellaneous checks
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if C-sources are US-ASCII
        run: |
          ! grep -r -n '[^	 -~]' *.[chy] include internal win32/*.[ch]
      - name: Check for trailing spaces
        run: |
          ! git grep -n '[	 ]$' '*.rb' '*.[chy]'
      - name: Check for header macros
        run: |
          ! for header in ruby/*.h; do \
            git grep -l -F -e $header -e HAVE_`echo $header | tr a-z./ A-Z__` -- . > /dev/null || echo $header
          done | grep -F .
        working-directory: include

      - name: Download default gems list
        run: |
          curl -O https://stdgems.org/default_gems.json

      - name: Make default gems list
        run: |
          require 'rubygems'
          $:.unshift "lib"
          rgver = File.foreach("lib/rubygems.rb") do |line|
            break $1 if /^\s*VERSION\s*=\s*"([^"]+)"/ =~ line
          end
          gems = Dir.glob("{ext,lib}/**/*.gemspec").map do |f|
            spec = Gem::Specification.load(f)
            "#{spec.name} #{spec.version}"
          end.sort
          File.open("stdlibs", "w") do |f|
            f.puts "RubyGems #{rgver}"
            f.puts gems
          end
        shell: ruby --disable=gems {0}

      - name: Maintain updated default gems list in NEWS
        run: |
          require 'json'
          news = File.read("NEWS.md")
          prev = news[/since the \*+(\d+\.\d+\.\d+)\*+/, 1]
          prevs = [prev, prev.sub(/\.\d+\z/, '')]
          last = JSON.parse(File.read("default_gems.json"))['gems'].filter_map do |g|
            v = g['versions'].values_at(*prevs).compact.first
            g = g['gem']
            g == 'RubyGems' if g == 'rubygems'
            "#{g} #{v}" if v
          end
          new = File.readlines('stdlibs', chomp: true).grep_v(/^#/)
          gems = new - last
          news.sub!(/^\*\s+The following default gems? are updated\.\K(\n\s+\*\s+).*(?:\1.*)*/) do
            ["", gems].join($1)
          end or exit
          File.write("NEWS.md", news)
        shell: ruby {0}

      - name: Check diffs
        id: diff
        run: |
          git diff --no-ext-diff --ignore-submodules --exit-code NEWS.md
        continue-on-error: true
      - name: Commit
        run: |
          git pull --ff-only origin ${GITHUB_REF#refs/heads/}
          git commit --message="Update stdlib version at ${GITHUB_SHA:0:30} [ci skip]" NEWS.md
          git push origin ${GITHUB_REF#refs/heads/}
        env:
          EMAIL: svn-admin@ruby-lang.org
          GIT_AUTHOR_NAME: git
          GIT_COMMITTER_NAME: git
        if: ${{ steps.diff.outcome == 'failure' }}
